package GUI;

import Algorithms.*;
import UtilsMethods.Utils;
import static UtilsMethods.Utils.messageWithBeep;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;


public class RC4_GUI extends javax.swing.JFrame {

    static File file,encryptDecryptFile,encryptedFile,decryptedFile;
    JFileChooser fileChooser=new JFileChooser();
    JFileChooser loadKeyChooser=new JFileChooser();
    JFileChooser saveKeyChooser=new JFileChooser();
    
    DES des;
    
    //update Resaults text area
    public static void updateResultsTextArea(String text){
        resultTextArea.append(text+"\n");
        resultTextArea.paintImmediately(resultTextArea.getBounds());
    }
    //update Input text area
    public static void updateInputTextArea(String text){
        inputTextArea.append(text+"\n");
        inputTextArea.paintImmediately(inputTextArea.getBounds());
    }
            
    public RC4_GUI() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("ico.png")).getImage());
        this.setTitle("DES Algorithm");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //files encrypt/decrypt
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Choose file to encrypt/decrypt!");
         //key load/save
        saveKeyChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        saveKeyChooser.setDialogTitle("Choose where to save AES key!");
        loadKeyChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        loadKeyChooser.setDialogTitle("Choose AES key!");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("AESKey","key");
        loadKeyChooser.setFileFilter(filter);
        //
        resultTextArea.setLineWrap(true);
        resultTextArea.setWrapStyleWord(true);
        //
        ChooseFileButton.setVisible(false);
        textRadioButton.setSelected(true);
        inputTextArea.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        inputTextLabel = new javax.swing.JLabel();
        fileRadioButton = new javax.swing.JRadioButton();
        textRadioButton = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        EncryptionButton = new javax.swing.JButton();
        ChooseFileButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DecryptionButton2 = new javax.swing.JButton();
        textInfoLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        keyTextField = new javax.swing.JTextField();
        LoadKeyButton = new javax.swing.JButton();
        SaveKeyButton = new javax.swing.JButton();
        GenerateKeysButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DecryptionButton1 = new javax.swing.JButton();
        resetKeyButton = new javax.swing.JButton();
        resetAllButton = new javax.swing.JButton();
        resetResultlButton = new javax.swing.JButton();
        resetTextButton = new javax.swing.JButton();
        resetFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        resultTextArea.setEditable(false);
        resultTextArea.setBackground(new java.awt.Color(204, 204, 204));
        resultTextArea.setColumns(20);
        resultTextArea.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        resultTextArea.setRows(5);
        jScrollPane1.setViewportView(resultTextArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(530, 70, 830, 660);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(null);

        inputTextLabel.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        inputTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputTextLabel.setText("Input Text here :");
        jPanel2.add(inputTextLabel);
        inputTextLabel.setBounds(10, 50, 120, 19);

        buttonGroup1.add(fileRadioButton);
        fileRadioButton.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        fileRadioButton.setText("FILE");
        fileRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileRadioButtonActionPerformed(evt);
            }
        });
        jPanel2.add(fileRadioButton);
        fileRadioButton.setBounds(370, 10, 59, 27);

        buttonGroup1.add(textRadioButton);
        textRadioButton.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        textRadioButton.setText("TEXT");
        textRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRadioButtonActionPerformed(evt);
            }
        });
        jPanel2.add(textRadioButton);
        textRadioButton.setBounds(160, 10, 65, 27);

        inputTextArea.setColumns(20);
        inputTextArea.setRows(5);
        inputTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputTextAreaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(inputTextArea);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 90, 490, 370);

        EncryptionButton.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        EncryptionButton.setText("Encryption");
        EncryptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncryptionButtonActionPerformed(evt);
            }
        });
        jPanel2.add(EncryptionButton);
        EncryptionButton.setBounds(10, 470, 150, 40);

        ChooseFileButton.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        ChooseFileButton.setText("Choose File");
        ChooseFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseFileButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ChooseFileButton);
        ChooseFileButton.setBounds(10, 40, 130, 40);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Encryption :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 10, 103, 24);

        DecryptionButton2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        DecryptionButton2.setText("Decryption");
        DecryptionButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecryptionButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(DecryptionButton2);
        DecryptionButton2.setBounds(340, 470, 160, 40);
        jPanel2.add(textInfoLabel);
        textInfoLabel.setBounds(150, 40, 350, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 210, 510, 520);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("NOTE : Key must be 16 characters in hexadecimal.");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 130, 490, 40);

        keyTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        keyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(keyTextField);
        keyTextField.setBounds(140, 20, 360, 40);

        LoadKeyButton.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        LoadKeyButton.setText("Load Key");
        jPanel3.add(LoadKeyButton);
        LoadKeyButton.setBounds(340, 80, 160, 40);

        SaveKeyButton.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        SaveKeyButton.setText("Save Key");
        jPanel3.add(SaveKeyButton);
        SaveKeyButton.setBounds(180, 80, 150, 40);

        GenerateKeysButton.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        GenerateKeysButton.setText("Generate Keys");
        GenerateKeysButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateKeysButtonActionPerformed(evt);
            }
        });
        jPanel3.add(GenerateKeysButton);
        GenerateKeysButton.setBounds(10, 80, 160, 40);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setText("KEY IN HEX");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 20, 120, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 10, 510, 180);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Results");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(530, 10, 170, 50);

        DecryptionButton1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        DecryptionButton1.setText("Decryption");
        jPanel1.add(DecryptionButton1);
        DecryptionButton1.setBounds(340, 470, 160, 40);

        resetKeyButton.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        resetKeyButton.setText("Reset Key");
        jPanel1.add(resetKeyButton);
        resetKeyButton.setBounds(850, 10, 117, 50);

        resetAllButton.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        resetAllButton.setText("RESET ALL");
        jPanel1.add(resetAllButton);
        resetAllButton.setBounds(1225, 10, 135, 50);

        resetResultlButton.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        resetResultlButton.setText("Reset Result");
        jPanel1.add(resetResultlButton);
        resetResultlButton.setBounds(710, 10, 140, 50);

        resetTextButton.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        resetTextButton.setText("Reset Text");
        jPanel1.add(resetTextButton);
        resetTextButton.setBounds(970, 10, 130, 50);

        resetFileButton.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        resetFileButton.setText("Reset File");
        jPanel1.add(resetFileButton);
        resetFileButton.setBounds(1100, 10, 120, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1374, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyTextFieldActionPerformed

    private void fileRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileRadioButtonActionPerformed
        
       ChooseFileButton.setVisible(true);
       
        inputTextArea.setText("");
        inputTextArea.setEditable(false);
        
        textInfoLabel.setVisible(true);
        textInfoLabel.setText("");
        
        inputTextLabel.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_fileRadioButtonActionPerformed

    private void textRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRadioButtonActionPerformed
       
        ChooseFileButton.setVisible(false);
        inputTextArea.setEditable(true);
        inputTextArea.setVisible(true);
        inputTextArea.setText("");
        inputTextLabel.setVisible(true);
        textInfoLabel.setVisible(true);
        textInfoLabel.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_textRadioButtonActionPerformed

    private void inputTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextAreaKeyReleased
         String text=inputTextArea.getText();
        long x=text.length();
        if(text.length()<=16 && text.length()>0)
            textInfoLabel.setText("Text size: "+text.length()+" bytes, "+
                    "Blocks num : "+1);
        else{
        if ((x % 16) ==0)
        textInfoLabel.setText("Text size: "+text.length()+" bytes, "+
                    "Blocks num : "+(text.length())/16);
        else
            textInfoLabel.setText("Text size: "+text.length()+" bytes, "+
                    "Blocks num : "+Math.round(((float)(text.length())/16)+0.5));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTextAreaKeyReleased

    private void ChooseFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseFileButtonActionPerformed
         if(fileChooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            encryptDecryptFile=fileChooser.getSelectedFile();
            textInfoLabel.setText(encryptDecryptFile.getAbsolutePath());
            long x=encryptDecryptFile.length();
            
         if(encryptDecryptFile.length()<=16 && encryptDecryptFile.length()>0)
             inputTextArea.setText("File size: "+encryptDecryptFile.length()+" bytes, "+
                    "Blocks num : "+1);
          else{
        if ((x % 16) ==0)
        inputTextArea.setText("File size: "+encryptDecryptFile.length()+" bytes, "+
                    "Blocks num : "+(encryptDecryptFile.length())/16);
        else
            inputTextArea.setText("File size: "+encryptDecryptFile.length()+" bytes, "+
                    "Blocks num : "+Math.round(((float)(encryptDecryptFile.length())/16)+0.5));
        }}
       else {
          messageWithBeep("No file choosen!\nplease choose a file first.");
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_ChooseFileButtonActionPerformed

    private void EncryptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncryptionButtonActionPerformed
        resultTextArea.setText("");
        //file encrypt
        if (fileRadioButton.isSelected()){
              if(encryptDecryptFile==null)
                  messageWithBeep("No file to encrypt!\nplease choose file first.");
              
              else{
                   try {
                       des=new DES();
                       //key
                       String key = keyTextField.getText();
                        key = des.fullString(key);
                        int[] keyBits = des.stringToBinary(key);
                        //file
                      byte[] plainFile=Files.readAllBytes(encryptDecryptFile.toPath());
                      updateResultsTextArea("file size befor encrypting = "+plainFile.length+" bytes");
                      String ss="";
                      for(int i=0;i<plainFile.length;i++){
                          ss+=String.format("%8s", Integer.toBinaryString(plainFile[i] & 0xFF).replace(' ', '0'));
                      }
                      
                      int[] inputBits = des.stringToBinary(ss);
                      //inputBits = Utils.fullInt(inputBits);
                       System.out.println(inputBits.length);
                      
                      int []res = des.permute(inputBits, keyBits, false);
                      byte []ress = Utils.intToByteArr(res);
                      FileOutputStream stream = new FileOutputStream(encryptDecryptFile.getAbsolutePath());
                      stream.write(ress);
                  } catch (IOException ex) {
                      Logger.getLogger(RC4_GUI.class.getName()).log(Level.SEVERE, null, ex);
                  }
              }
        }
        //text encrypt
        else if(textRadioButton.isSelected()){
            //get plain text from input
            String plainText=inputTextArea.getText();
            if (plainText.equals(""))
                messageWithBeep("No text to encrypt!\nplease enter text first.");
            
            else{
                des=new DES();
                
                String key = keyTextField.getText();
                key = des.fullString(key);
                int[] keyBits = des.stringToBinary(key);
                
                String input = inputTextArea.getText();
                input = des.fullString(input);
                //int []inBits = des.stringToBinary(input);
                int j=1;
                for(int i=0;i<input.length();i+=16){
                  int[] inputBits = des.stringToBinary(input.substring(i, i+16));
                  updateResultsTextArea("Block "+j);
                 int []res = des.permute(inputBits, keyBits, false);
                 updateResultsTextArea("----------------------------------------");
                 j++;
                }
                updateResultsTextArea(des.finalOut);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_EncryptionButtonActionPerformed

    private void DecryptionButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecryptionButton2ActionPerformed
        resultTextArea.setText("");
        //file encrypt
        if (fileRadioButton.isSelected()){
              if(encryptDecryptFile==null)
                  messageWithBeep("No file to encrypt!\nplease choose file first.");
              else{
                  try {
                      des=new DES();
                      String key = keyTextField.getText();
                      key = des.fullString(key);
                      int[] keyBits = des.stringToBinary(key);
                      
                      byte[] plainFile=Files.readAllBytes(encryptDecryptFile.toPath());
                      updateResultsTextArea("file size befor encrypting = "+plainFile.length+" bytes");
                      String s = Utils.bytesToHex(plainFile);
                      //s = des.fullString(s);
                      int[] inputBits = des.stringToBinary(s);
                      inputBits = Utils.fullInt(inputBits);
                      System.out.println(inputBits.length);
                      
                      int []res = des.permute(inputBits, keyBits, true);
                      byte []ress = Utils.intToByteArr(res);
                      FileOutputStream stream = new FileOutputStream(encryptDecryptFile.getAbsolutePath());
                      stream.write(ress);
                  } catch (IOException ex) {
                      Logger.getLogger(RC4_GUI.class.getName()).log(Level.SEVERE, null, ex);
                  }
              }
        }
        //text encrypt
        else if(textRadioButton.isSelected()){
            //get plain text from input
            String plainText=inputTextArea.getText();
            if (plainText.equals(""))
                messageWithBeep("No text to encrypt!\nplease enter text first.");
            
            else{
                des=new DES();
                
                String key = keyTextField.getText();
                key = des.fullString(key);
                int[] keyBits = des.stringToBinary(key);
                String input = inputTextArea.getText();
                int j=1;
                for(int i=0;i<input.length();i+=16){
                  int[] inputBits = des.stringToBinary(input.substring(i, i+16));
                  updateResultsTextArea("Block "+j);
                 int []res = des.permute(inputBits, keyBits, true);
                 updateResultsTextArea("----------------------------------------");
                 j++;
                }
                updateResultsTextArea(des.finalOut);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_DecryptionButton2ActionPerformed

    private void GenerateKeysButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateKeysButtonActionPerformed
        des=new DES();
                
                String key = keyTextField.getText();
                //key = des.fullString(key);
                int[] keyBits = des.stringToBinary(key);
                for(int i=0;i<16;i++){
                  int[]k = des.KS(i, keyBits);
                  updateResultsTextArea(des.displayBitsString(k));
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateKeysButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RC4_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RC4_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RC4_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RC4_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RC4_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChooseFileButton;
    private javax.swing.JButton DecryptionButton1;
    private javax.swing.JButton DecryptionButton2;
    private javax.swing.JButton EncryptionButton;
    private javax.swing.JButton GenerateKeysButton;
    private javax.swing.JButton LoadKeyButton;
    private javax.swing.JButton SaveKeyButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton fileRadioButton;
    private static javax.swing.JTextArea inputTextArea;
    private javax.swing.JLabel inputTextLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField keyTextField;
    private javax.swing.JButton resetAllButton;
    private javax.swing.JButton resetFileButton;
    private javax.swing.JButton resetKeyButton;
    private javax.swing.JButton resetResultlButton;
    private javax.swing.JButton resetTextButton;
    public static javax.swing.JTextArea resultTextArea;
    private javax.swing.JLabel textInfoLabel;
    private javax.swing.JRadioButton textRadioButton;
    // End of variables declaration//GEN-END:variables
}
